### ISSUE TITLE
Make building blocks importable.

### ISSUE THREAD

**Issue by pbalogh-sa** [CycloneDX/cyclonedx-gomod#108]
It would be nice if the building block can be importable.
I think if the necessary directories are put into `pkg` dir instead of `internal` (mostly all of them except `cli`), it should be work.

**Comment by nscuro** [comment]
Related to #99. We will probably expose the "surface logic" provided by the CLI in one of the next releases. But a lot of the internal logic is not quite ready for public consumption, and we're not comfortable in making any stability guarantees for them. 

What exactly do you mean with "building block"? Is there a specific functionality that you need?

**Comment by pbalogh-sa** [comment]
I want to use the `cyclonedx-gomod` analyzer in my go implementation which runs the analyzers and provides the BOM results for further steps.
