### ISSUE TITLE
Add support for license resolution

### ISSUE THREAD

**Issue by nscuro** [CycloneDX/cyclonedx-gomod#2]
Go currently has no way to define a module's license. [pkg.go.dev does display license information](https://pkg.go.dev/github.com/CycloneDX/cyclonedx-go?tab=licenses), but that's not really accurate and relies on Google's license detection.

Similarly, licenses for modules hosted on GitHub could be retrieved using the GitHub REST API. Responses of the [`/repos` endpoint](https://docs.github.com/en/rest/reference/repos#get-a-repository) includes license information.

Another way would be to use license detection mechanisms like the one provided by [go-license-detector](https://github.com/go-enry/go-license-detector). Although the detection appears to be quite good, we can't be 100% sure. The question arises if including licenses in the BOM that possibly aren't accurate is better than not including any at all.

For starters, this could be implemented as opt-in feature.

**Comment by coderpatros** [comment]
I should refactor this functionality in the .NET tool so it is available in the CLI tool.

**Comment by nscuro** [comment]
@coderpatros Great suggestion. I'll attempt to resolve module paths to a GitHub repository and add it as external reference then.

**Comment by nscuro** [comment]
Seems like we can never be 100% certain about the license info. All sources employ a best effort approach, which is better than nothing I guess. I'll implement a lookup mechanism using pkg.go.dev, as it appears to be the most reliable source we currentlly have (see [disclaimer](https://pkg.go.dev/license-policy) regarding detection accuracy). 

We should make this transparent to our users as well and most definitely make this feature opt-in, at least until we find a 100% reliable source.
