### ISSUE TITLE
Can you please cut a new release?

### ISSUE THREAD

**Issue by FrimIdan** [CycloneDX/cyclonedx-gomod#281]
Due to breaking changes introduce in github.com/CycloneDX/cyclonedx-go v0.7.0 (https://github.com/CycloneDX/cyclonedx-go/commit/ea0d5b79fe245884a46d7537271d0d951d46ad1a) and since your latest tag is pointing to an old version, is it possible for you to cut a new release? (you already point to v0.7.0 in main)

**Comment by nscuro** [comment]
On it, thanks for the ping.

**Comment by nscuro** [comment]
Done: https://github.com/CycloneDX/cyclonedx-gomod/releases/tag/v1.4.0
