### ISSUE TITLE
Question: make LoadModulesFromBinary public?

### ISSUE THREAD

**Issue by imjasonh** [CycloneDX/cyclonedx-gomod#99]
Hello 👋 

I maintain [`ko`](https://github.com/google/ko/), a tool for building Go applications into lightweight container images. It's got [somewhat basic support today](https://github.com/google/ko/blob/main/doc/ko_deps.md) for generating "SBOMs", which is effectively to extract the Go binary and run `go version -m` on it, and print that to stdout. It's not pretty but it works.

I'd love to augment this with "real" SBOM support in as many formats as I can get, and have SBOMs generated and uploaded to registries, instead of just extracted from binaries at request-time. (Or maybe some future where we ensure the binary's embedded information matches the pushed SBOM? Unclear.)

Anyway, I'd love to be able to skip writing code to translate the output of `go version -m` to CycloneDX SBOM if I can avoid it, and I see that this repo already has that written in an internal package, in `LoadModulesFromBinary`:

https://github.com/CycloneDX/cyclonedx-gomod/blob/b5f7b634799c09820eae24da6a4a079eba5b12e6/internal/gomod/binary.go#L29

Is there any interest in moving this to a non-`internal` package, where I could vendor it into `ko`?

**Comment by nscuro** [comment]
Hi Jason 👋

Hell yeah, sounds like a great idea to me! 
Although I wouldn't expose functions like `LoadModulesFromBinary` that work on internal models. 
I think I can expose the "top-level" functionality provided by the CLI, as in "give me a binary path and I give you a [BOM](https://pkg.go.dev/github.com/CycloneDX/cyclonedx-go#BOM)".

**Comment by imjasonh** [comment]
> Hell yeah, sounds like a great idea to me! Although I wouldn't expose functions like `LoadModulesFromBinary` that work on internal models. I think I can expose the "top-level" functionality provided by the CLI, as in "give me a binary path and I give you a [BOM](https://pkg.go.dev/github.com/CycloneDX/cyclonedx-go#BOM)".

That sounds fine too. I had found `LoadModulesFromBinary` as what seemed like the highest-level thing that the `bin` CLI surface calls:

https://github.com/CycloneDX/cyclonedx-gomod/blob/v1.0.0/internal/cli/cmd/bin/bin.go#L84

But a method that just took a binary path (maybe even an `io.ReaderAt` after Go 1.18 🙏 ) and returned a `BOM` that I could encode and output/store would be fantastic. 🤩 

Thanks for being receptive to it, and let me know if I can help review in any way 👍

**Comment by nscuro** [comment]
> maybe even an io.ReaderAt after Go 1.18 🙏

Woah, didn't notice that the Go team added this functionality to the stdlib. [That](https://github.com/golang/go/blob/85a068fdf21bd2e4475a87ee049af4fbe797bcbe/src/debug/buildinfo/buildinfo.go#L73) will certainly make my life a lot easier. 🥳

**Comment by imjasonh** [comment]
Just wanted to drop in and say thanks again for taking on this work! I'm excited to incorporate it in our projects. 🏅
